### PR TITLE
Add Alert to Submission Page When User has No Algorithms

### PR DESCRIPTION
**Pull request by james-milburn-crowe**
Replaces the small create algorithm link with a large create algorithm button on the phase submission page

Capture

Part of #2998

### CODE REVIEW

**Comment by jmsmkn** [comment]
Buttons there are to do with form submission, should be reserved for saving, cancelling, deleting etc. I think a new section is better, that is rendered instead of the form if the user does not have a valid algorithm, that explains that this is an algorithm submission phase and that they first need to set up their algorithm.

**Comment by james-milburn-crowe** [comment]
> Buttons there are to do with form submission, should be reserved for saving, cancelling, deleting etc. I think a new section is better, that is rendered instead of the form if the user does not have a valid algorithm, that explains that this is an algorithm submission phase and that they first need to set up their algorithm.

I'll put a section together

**Comment by james-milburn-crowe** [comment]
It took a little work to get this showing up properly - 
Capture45
I have one last thing to check tomorrow, but if this looks ok, then it'll be done!

**Comment by james-milburn-crowe** [comment]
This is all done and working (no rush on reviews, I just wanted to check it wasn't languishing because you were waiting for input from me)

**Pull request closed without merging**
