### PR TITLE
Add missing filter fields to swagger docs

### LINKED ISSUE #2479: `unanswered_by_user` and `user` options are missing from the Display Set documentation
**Describe the bug**
The swagger documentation should show all the filters available, they are missing from https://grand-challenge.org/api/#/reader-studies/reader_studies_display_sets_list

**Screenshots**
image

### PR DESCRIPTION
**Pull request by MikeOverkamp-diag**
Closes #2479

### CODE REVIEW

**Comment by jmsmkn** [comment]
Could you add a test for this? We're using an ancient, beta, version of spectacular and the API may have changed by the time we upgrade (#1738)

**Comment by MikeOverkamp-diag** [comment]
This is based on the docs for the latest version btw: https://drf-spectacular.readthedocs.io/en/latest/customization.html

**Comment by jmsmkn** [comment]
Probably it is doing something to the serializer and you can test that directly.

**Comment by MikeOverkamp-diag** [comment]
I think the test is a bit iffy still, but it's the best I could do. At least we'll have a reminder to look at this part of the code if we ever do upgrade.

**Comment by jmsmkn** [comment]
Why not test against the actual generated schema returned by this view? https://github.com/comic/grand-challenge.org/blob/7a5403adacbed60d596ea8ea749440bf94393bcb/app/grandchallenge/api/urls.py#L185

**Review by jmsmkn — APPROVED** [review]

**Pull request merged**
