### PR TITLE
fix for hanging protocols displaying incorrectly on hanging protocol cards

### PR DESCRIPTION
**Pull request by james-milburn-crowe**
A small fix for #3009  - the issue was that z-indexes were being set as negative, causing viewports with an order >0 to appear behind the card

We have a max of 20 viewpoints, and therefore I've set z-index to count down from 20, rather than going negative. 

This keeps the correct ordering, but stops things from being placed behind the cards

We could also set card z-index to -99 or similar, but I think that is more likely to cause some future unforeseen bootstrap issues

### CODE REVIEW

**Comment by HarmvZ** [comment]
I slightly improved your implementation by using the max value for `order` to determine the values for z-index. This is better because we currently do not put constraints on the usage of `order` except that it should be an integer. This improvement should work for any integer value.

In the meantime, I got in a fight with pycharm/git and line endings - that's fixed now.

**Comment by james-milburn-crowe** [comment]
ah, thanks! that makes sense - but I think this might go negative - we'd like to avoid z-index being negative, as it puts the item behind the cards

**Comment by james-milburn-crowe** [comment]
just fixing, not ready for merge - it's a much nicer solution, but maxOrder is currently being set to NaN, and so z-index is just removed completely. Which still makes the rendering work much more nicely, so honestly we could consider doing that

**Comment by jmsmkn** [comment]
Converting to draft in that case.

**Comment by james-milburn-crowe** [comment]
> > but I think this might go negative
> 
> It shouldn't. How do you think so?

Ah, sorry, my maths was off! works perfectly!

**Review by jmsmkn — APPROVED** [review]

**Pull request merged**
