### PR TITLE
Make all inputs required on job creation

### PR DESCRIPTION
**Pull request by amickan**
Addresses the job stuck in `VALIADTING_INPUTS` from this morning.

### CODE REVIEW

**Review by jmsmkn — DISMISSED** [review]

**Comment by jmsmkn** [comment]
It looks like the API test needs to be updated too.

**Comment by amickan** [comment]
> It looks like the API test needs to be updated too.

I didn't touch the API code. All inputs are required there already. The test that failed passes locally for me, so I'm rerunning the tests here

**Comment by jmsmkn** [comment]
Sorry, thought it was an API test but I was mistaken. It is a test which touches this view, probably a wrong assumption there. Very strange that it passes locally as it has failed again.

**Comment by amickan** [comment]
> It is a test which touches this view, probably a wrong assumption there. Very strange that it passes locally as it has failed again.

Strange indeed. I've tried a few times, but can't get it to fail locally. I have to go now, will revisit this on Wednesday.

**Comment by jmsmkn** [comment]
Root cause: the test `test_job_gpu_type_set_with_api` that I added in #3586 did not actually use the api view but the template view, which was changed here. Now fixed. Can't explain the differences between CI and your machine, but it also failed on mine. Please double check your setup.

**Pull request merged**
