### PR TITLE
change hyper link color default and overwrite default in product_list

### PR DESCRIPTION
**Pull request by Kicksta**
When I started developing I didn't want the hyperlinks to show up blue in the product_list, so I made default black and manually make them blue when wanted blue. However when writing the blogs I realized I want the default to be blue and only have them suppressed in the product_list. So I only overwrite it there now by adding a separate stylesheet.

### CODE REVIEW

**Comment by MikeOverkamp-diag** [comment]
Rather than styling the `a` element and using a separate stylesheet, I'd prefer if you styled the links based on classes and add a separate class for the links in the products list.

**Comment by Kicksta** [comment]
Do I understand correctly if you mean adding e.g.`.text-dark {
    color: #212529;
}` to main.css.
And using it as follows in all places i want it to appear differently? 
`<a class=text-dark href= "{% url 'products:company-detail' slug=product.company.slug %}" title={{product.company.company_name}} >{{ product.company.company_name }}</a>
`

**Comment by jmsmkn** [comment]
Don't know if it helps but there are existing classes for this already in bootstrap https://getbootstrap.com/docs/4.0/utilities/colors/

**Comment by Kicksta** [comment]
okay thanks. I am going to throw away this branch and start over in this much simpler manner ;p

**Pull request closed without merging**
