### PR TITLE
Allow display set deletion in UI

### PR DESCRIPTION
**Pull request by MikeOverkamp-diag**

### CODE REVIEW

**Review by jmsmkn — COMMENTED** [review]
This looks fine but we need tests, especially for deletion. Cover permissions and whether answers are there.

**Comment by MikeOverkamp-diag** [comment]
Sorry, was a bit too hasty with this one. Added the test.

**Comment by MikeOverkamp-diag** [comment]
Copy/paste error in the test, needs a small fix still

**Comment by MikeOverkamp-diag** [comment]
Fixed now.

**Review by jmsmkn — APPROVED** [review]

**Pull request merged**
