### PR TITLE
Separate interface lists for reader studies and archives

### PR DESCRIPTION
**Pull request by miriam-groeneveld**
Well, I thought that would be a quick and simple fix, but was a bit more complicated than I thought. I opted for creating new pages for the different contexts, that required a copy of the AddCasesForm for reader studies to be able to reference the correct url. Alternative was to cram everything into the single componentsinterface_list.html, which became quite messy.

### CODE REVIEW

**Review by jmsmkn — COMMENTED** [review]
Looks good, shame that it seems like a lot of duplication, this looks like it should be solvable with parametrisation (maybe by moving the view out of algorithms/archives/reader studies and into the components app, and have it routed from the top level). Could you add tests for the new views and form?

**Comment by miriam-groeneveld** [comment]
Agree about the duplication, but using parameters became very messy with the breadcrumbs. I tried that as well: https://github.com/comic/grand-challenge.org/compare/specified_interface_lists_2?expand=1
Not sure which one I prefer.

**Comment by jmsmkn** [comment]
Yes, that's what I mean about moving it to the top level - avoid the breadcrumb problem by moving it out of each app and to the top level. No good example but something like this https://grand-challenge.org/about/, would then be like an interfaces flatpage (but not actually a flatpage). You could even make it a special part of the documentation app. Maybe that's better?

**Comment by miriam-groeneveld** [comment]
> Yes, that's what I mean about moving it to the top level - avoid the breadcrumb problem by moving it out of each app and to the top level. No good example but something like this https://grand-challenge.org/about/, would then be like an interfaces flatpage (but not actually a flatpage). You could even make it a special part of the documentation app. Maybe that's better?

Ah, I see what you mean regarding moving it to the toplevel, that would be better yes. How would moving it to the documentation app work, create a interfaces folder within the documentation templates folder and move it all there? With comparable parameters to distinguish the various contexts?

**Comment by jmsmkn** [comment]
Maybe @amickan has some thoughts on the structure?

**Comment by miriam-groeneveld** [comment]
Closed in favour of new PR: #2485

**Pull request closed without merging**
