### PR TITLE
Disable resizing for markdown editor

### LINKED ISSUE #2520: Markdown Editor jumps around too much
When editing in Markdown the Grand Challenge editor jumps around a lot, so the writer loses their place.

https://user-images.githubusercontent.com/12661555/173570208-c2567b82-bb78-441c-9286-2f70a8f66745.mp4

It would be better if the size of the text area was kept constant, and the content only resized when switching to the preview tab, like on GitHub:

https://user-images.githubusercontent.com/12661555/173570346-97f51fa9-fc23-49e8-b587-f656ff3cb7db.mp4

### PR DESCRIPTION
**Pull request by amickan**
Closes #2520 

https://user-images.githubusercontent.com/30069334/174264228-d76a079d-adcc-4331-8f09-41378f8c6675.mp4

### CODE REVIEW

**Comment by jmsmkn** [comment]
The preview tab no longer works, check the JS console and follow the workflow that I demonstrated in #2520 when testing. I think this was the problem as the content there was resizing.

**Comment by amickan** [comment]
> The preview tab no longer works, check the JS console and follow the workflow that I demonstrated in #2520 when testing. I think this was the problem as the content there was resizing.

The preview tab works fine for. I will take a look at the error though.

**Comment by jmsmkn** [comment]
Hmm, definitely not for me, I was on the algorithm update page in FireFox.

**Comment by amickan** [comment]
Very strange. It works for me, both in Firefox and Chrome on the blog post pages and the algorithm page. Also tried on the archive and reader study and documentation pages. I fixed the error now. Can you try again?

**Comment by jmsmkn** [comment]
Works now!

**Review by jmsmkn — APPROVED** [review]

**Pull request merged**
