### PR TITLE
Add a view to delete combined leaderboards

### PR DESCRIPTION
**Pull request by chrisvanrun**
Part of the pitch:
- https://github.com/DIAGNijmegen/rse-roadmap/issues/243

This changeset adds a view that allows challenger admins to delete a combined leaderboard.

It also does a minor fix on the leaderboards not being visible when viewing an evaluation detail.

### CODE REVIEW

**Review by miriam-groeneveld — APPROVED** [review]
Besides the tiny grammar things, looks okay to me.

**Review by miriam-groeneveld — APPROVED** [review]

**Comment by chrisvanrun** [comment]
I think the default handling of PR mergers is somewhat different in GC than in CIRRUS. A lot of conflicts result from the regular chained PRs.

**Comment by chrisvanrun** [comment]
I've just merged the update cache time on top of this, as to prevent even more conflicts after merging this...

**Comment by chrisvanrun** [comment]
@miriam-groeneveld could you screen this and re-approve following some fixes?

**Review by miriam-groeneveld — APPROVED** [review]

**Pull request merged**
