### PR TITLE
Add environment variable for session control timeout

### PR DESCRIPTION
**Pull request by amickan**
This adds a `WORKSTATIONS_SESSION_CONTROL_TIMEOUT` environment variable to easily change the timout in production.

### CODE REVIEW

**Comment by jmsmkn** [comment]
Is this not way too fine detail? I can't see sites wanting to modify this, if we get it wrong first time we could change the value in the js file and re-deploy.

**Comment by chrisvanrun** [comment]
> Is this not way too fine detail? I can't see sites wanting to modify this, if we get it wrong first time we could change the value in the js file and re-deploy.

It is indeed fine. But I suspect this will likely need ongoing tweaking during integration and hooks heavily on what CIRRUS does:
* we will want to likely integrate these changes next week which will not see the CIRRUS release, we want to reduce the extra start-up time for sessions as much as possible.
* once CIRRUS is released we can see if it generally feels ok or is too flaky at 1s.

If re-deployment is just as easily done (or nearly) as tweaking production envs @amickan I suggest we put it at 1s by default and see what it does.

**Comment by amickan** [comment]
Yes, both cases require a one line change and a redeploy, so it doesn't really matter which way we go. But just changing the default in the js code clutters the buttons less, so maybe that is preferred after all. I will close this PR and change the default for the timeout to 1s in the other PR I'm working on.

**Comment by chrisvanrun** [comment]
Check! I am used to CIRRUS where deploying is something quite heavy.

**Pull request closed without merging**
