### PR TITLE
Extends the algorithm API

### LINKED ISSUE #1314: Algorithm Results API improvements
We would like to:

- [x] Get all of the results for a particular algorithm (filtered by the users permissions)
- [x] For an algorithm result, get a list of the output files, the metrics json, and the input files (without going through the job)
- [ ] Extract data from the metrics json (#1070)
- [x] Ensure the API is fast, check the number of db calls

### PR DESCRIPTION
**Pull request by jmsmkn**
This PR:

- Allows filtering of algorithm images, jobs, and results by the algorithms uuid
- Serializes the job to the results json rather than having to make another lookup for each result
- Speeds up the reader study list view

Closes #1314

### CODE REVIEW

**Comment by pkcakeout** [comment]
Could you provide a few samples on what is new and now possible after this PR? I am way too rusty in reading this declarative style. Matching the change set up with a one or two examples would be helpful.

**Comment by jmsmkn** [comment]
eg, we could give CIRRUS `algorithmResult=4a687cda-13a7-4294-8c8c-538e35c16832`. Then, `https://gc.localhost/api/v1/algorithms/results/4a687cda-13a7-4294-8c8c-538e35c16832/` now returns:

```
{
  "pk": "4a687cda-13a7-4294-8c8c-538e35c16832",
  "api_url": "https://gc.localhost/api/v1/algorithms/results/4a687cda-13a7-4294-8c8c-538e35c16832/",
  "job": {
    "pk": "4fef2450-3fbf-4f5b-915e-87611959919d",
    "api_url": "https://gc.localhost/api/v1/algorithms/jobs/4fef2450-3fbf-4f5b-915e-87611959919d/",
    "algorithm_image": "https://gc.localhost/api/v1/algorithms/images/e6fc4a74-a5bd-43d8-b42f-98debb8bc96e/",
    "image": "https://gc.localhost/api/v1/cases/images/42df51ab-140e-4f56-9e31-fa638bf8adb4/",
    "result": "https://gc.localhost/api/v1/algorithms/results/4a687cda-13a7-4294-8c8c-538e35c16832/",
    "status": "Succeeded"
  },
  "images": [
    "https://gc.localhost/api/v1/cases/images/d5def706-2fa0-4c61-a4be-3c0255f61268/"
  ],
  "output": {
    "entity": [
      "42df51ab-140e-4f56-9e31-fa638bf8adb4.mha"
    ],
    "metrics": [
      {
        "file": "filepath:42df51ab-140e-4f56-9e31-fa638bf8adb4.mha",
        "threshold": 2175
      }
    ],
    "error_messages": []
  },
  "import_session": "https://gc.localhost/api/v1/cases/upload-sessions/7d810fbc-b688-4b47-9bdb-a53cb39730d6/"
}
```

The job part now serialized rather than being a hyperlink, `job.image` is the input image, `images` are the output images.

We could also get all of the results for an algorithm by giving CIRRUS, say, "algorithm=8803e8ab-de67-4fbe-874d-8b712297e340". Then we can get a list of all of the results objects that the user has permission to view for this algorithm at `https://gc.localhost/api/v1/algorithms/results/?job__algorithm_image__algorithm=8803e8ab-de67-4fbe-874d-8b712297e340`:

```
{
  "count": 2,
  "next": null,
  "previous": null,
  "results": [
    {
      "pk": "4a687cda-13a7-4294-8c8c-538e35c16832",
      "api_url": "https://gc.localhost/api/v1/algorithms/results/4a687cda-13a7-4294-8c8c-538e35c16832/",
      "job": {
        "pk": "4fef2450-3fbf-4f5b-915e-87611959919d",
        "api_url": "https://gc.localhost/api/v1/algorithms/jobs/4fef2450-3fbf-4f5b-915e-87611959919d/",
        "algorithm_image": "https://gc.localhost/api/v1/algorithms/images/e6fc4a74-a5bd-43d8-b42f-98debb8bc96e/",
        "image": "https://gc.localhost/api/v1/cases/images/42df51ab-140e-4f56-9e31-fa638bf8adb4/",
        "result": "https://gc.localhost/api/v1/algorithms/results/4a687cda-13a7-4294-8c8c-538e35c16832/",
        "status": "Succeeded"
      },
      "images": [
        "https://gc.localhost/api/v1/cases/images/d5def706-2fa0-4c61-a4be-3c0255f61268/"
      ],
      "output": {
        "entity": [
          "42df51ab-140e-4f56-9e31-fa638bf8adb4.mha"
        ],
        "metrics": [
          {
            "file": "filepath:42df51ab-140e-4f56-9e31-fa638bf8adb4.mha",
            "threshold": 2175
          }
        ],
        "error_messages": []
      },
      "import_session": "https://gc.localhost/api/v1/cases/upload-sessions/7d810fbc-b688-4b47-9bdb-a53cb39730d6/"
    }
  ]
}
```

**Comment by pkcakeout** [comment]
Yeah, that both sounds great. We could also just add both, right? Add algorithm and algorithmResult  to the URL? Then we have "maximum freedom" and can go both ways: Have a readerstudy-style browser interface (more complex) or just show the current result (probably our first quick solution) and we do not need to redeploy. I expect that long-term we will prefer the algorithm-route over the specific algorithmResult.

With regards to that two more questions:

- `job__algorithm_image__algorithm` - does that expose only one foreign key relation which goes via algorith_image. So job->algoritm_image->algorithm, I assume?
- I think a filtering jobs on input-image AND algorithm would be very handy to have, if we want to add a browser to the algorithm results viewer. Querying all results all the time just to find a specific result for a specific image  might be inefficient if we have a lot results. So maybe we can add a specific query for this to allow us obtaining a specific result for a specific image+algorithm?

**Comment by jmsmkn** [comment]
1. Yes
2. Done! `https://gc.localhost/api/v1/algorithms/results/?job__algorithm_image__algorithm=8803e8ab-de67-4fbe-874d-8b712297e340&job__image=42df51ab-140e-4f56-9e31-fa638bf8adb4`

I can add the `algorithm=` or `algorithmResult=` url links once implemented in CIRRUS and deployed.

**Pull request merged**
