### PR TITLE
Add image port mapping field

### PR DESCRIPTION
**Pull request by MikeOverkamp-diag**

### CODE REVIEW

**Review by amickan — APPROVED** [review]
Looks great!

**Comment by jmsmkn** [comment]
Definitely should only be a warning. Maybe it should be a in the viewer? I imagine that we will one day have the ability to dynamically switch out hanging protocols. I guess you could add the hanging protocol info in the admin section of the algorithm detail page, and show a warning there.

**Comment by MikeOverkamp-diag** [comment]
Do we want the message to always be there on a mismatch? It is fairly easy to add a warning post save in the admin, but I'd say that is of limited use. If we want it to be there permanent, I think that's a bit more work and I'd propose to move that to a separate PR.

**Comment by MikeOverkamp-diag** [comment]
Renamed the field and updated the help text. Accidentally rebased in the process, hence the force push. Apologies.

**Review by jmsmkn — APPROVED** [review]

**Pull request merged**
