### PR TITLE
Fix json file input on try out algorithm

### PR DESCRIPTION
**Pull request by amickan**
Addresses https://github.com/DIAGNijmegen/rse-grand-challenge-admin/issues/101

### CODE REVIEW

**Review by jmsmkn — APPROVED** [review]

**Comment by jmsmkn** [comment]
@amickan I'm looking at uses of `is_file_kind` - does the same problem exist in `AlgorithmExperimentCreate`, `update_archive_item_update_kwargs`, `ArchiveEditArchiveItem`, or `ComponentInterfaceValuePostSerializer`? Is the test `test_algorithm_multiple_inputs` correct? I find this API a little confusing.

**Comment by amickan** [comment]
> @amickan I'm looking at uses of `is_file_kind` - does the same problem exist in `AlgorithmExperimentCreate`, `update_archive_item_update_kwargs`, `ArchiveEditArchiveItem`, or `ComponentInterfaceValuePostSerializer`? Is the test `test_algorithm_multiple_inputs` correct? I find this API a little confusing.

Good point. I will double check and make changes as necessary.

**Comment by amickan** [comment]
I have checked all places where we use `is_file_kind` and replaces them with `requires_file` when necessary. I also added some tests. 

One thing that is not covered yet is running an algorithm job with a json input (not stored in db) through the API. That will require some changes in gcapi, maybe @MikeOverkamp-diag can have a look?

**Comment by jmsmkn** [comment]
> I have checked all places where we use `is_file_kind` and replaces them with `requires_file` when necessary. I also added some tests.
> 
> One thing that is not covered yet is running an algorithm job with a json input (not stored in db) through the API. That will require some changes in gcapi, maybe @MikeOverkamp-diag can have a look?

Is that being done in https://github.com/DIAGNijmegen/rse-gcapi/pull/136?

**Comment by MikeOverkamp-diag** [comment]
> > I have checked all places where we use `is_file_kind` and replaces them with `requires_file` when necessary. I also added some tests.
> > One thing that is not covered yet is running an algorithm job with a json input (not stored in db) through the API. That will require some changes in gcapi, maybe @MikeOverkamp-diag can have a look?
> 
> Is that being done in [DIAGNijmegen/rse-gcapi#136](https://github.com/DIAGNijmegen/rse-gcapi/pull/136)?

No that's just the updated api for reader studies. I can have a look at the algorithm stuff this week.

**Review by jmsmkn — APPROVED** [review]

**Pull request merged**
