### PR TITLE
Cache the product list for 1 hour

### PR DESCRIPTION
**Pull request by jmsmkn**
Assumes that the contents of products/partials/product_list.html
only varies with the query string

### CODE REVIEW

**Review by MikeOverkamp-diag — APPROVED** [review]

**Comment by Kicksta** [comment]
Search and filtering works.
Logo's don't show anymore (Shows image icon + alt string).
The main page: https://gc.localhost/aiforradiology/, shows no products but states 19/19 results. I have to filter or search to get to see the products. I guess this discrepancy will last for an hour then because it cached the 'empty state'?

**Comment by jmsmkn** [comment]
Did you load the page before populating the database?

Logos not loading would be very strange.

**Comment by Kicksta** [comment]
Yes, I loaded the page before populating the database. I now removed cache from my browser, but problem persists (is this the right way to check?). I switched to master and I get to see the database again while being on the homepage. Switched back to branch, and no products are shown.

Logo problem is also on master with cycle-docker-compose on branch.
When on master with cycle-docker-compose on master, logo's are visible again.

**Comment by jmsmkn** [comment]
What happens on the branch if you change `{% cache 3600 product_list request.META.QUERY_STRING %}` to `{% cache 3600 product_list_test request.META.QUERY_STRING %}` and refresh the page?

**Comment by Kicksta** [comment]
homepage list is not empty

**Comment by jmsmkn** [comment]
So it looks ok? Do the logos work?

**Comment by Kicksta** [comment]
Okay i am again intrigued by the mystery of computers. 
On branch, i did again cycledockercompose.
Then went directly to aiforradiology/import-data. Uploaded database. Went to homepage: logo's work, database list shows. With the original line of code `{% cache 3600 product_list request.META.QUERY_STRING %}`.

Conclusion: original review request approved. Sorry for the hassle 🥴

**Comment by jmsmkn** [comment]
It's ok! Yes, that is what I expected, caches are difficult and probably easier to explain what is going on synchronously, and we should try to find an easier way to test this in development so that I can do it too. When you're working on this template in development it will be easiest to drop the cache period to `1`s, rather than `3600`s.

**Pull request merged**
