### PR TITLE
Add migration to move reader studies to new setup

### PR DESCRIPTION
**Pull request by MikeOverkamp-diag**
We probably should not merge this until Monday, as it adds a warning to any reader study that does not have `use_display_sets` set to True.

### CODE REVIEW

**Review by jmsmkn — COMMENTED** [review]
Looks good, but the migration of each study should be in an atomic block

**Comment by jmsmkn** [comment]
Also do we need to prevent new answers being created for a study whilst it is being migrated?

**Comment by jmsmkn** [comment]
Can you add something to detect this at the end of the migration for each RS?

**Comment by jmsmkn** [comment]
Also please add logging as we go so we have insights on the progress.

**Comment by MikeOverkamp-diag** [comment]
> Can you add something to detect this at the end of the migration for each RS?

Done, but I'm not sure how to add that bit to the test.

**Comment by MikeOverkamp-diag** [comment]
I'm considering not putting this in a management command, but making it a button in the view, like the `Generate hanging list` button. The way I picture this, is that we have users define the view content first, that way we know what interface to use for what image. By going this route, we are not limited to just main and main-overlay, but can use any interface and as many viewports as needed. What do you think @jmsmkn?

**Comment by jmsmkn** [comment]
I think we should still keep this so that we handle it for the simple cases, but indeed other studies will need a path forward and that sounds like a fine idea.

**Review by jmsmkn — APPROVED** [review]

**Pull request merged**
