### PR TITLE
Reduce load-time of the reader-study detail page

### LINKED ISSUE #1158: Reader study detail page is slow for editors
With many readers the reader study detail page has slowed down for the reader study editor (28 readers, almost 1s TTFB). 

We should try to optimise some of these queries, and split up the pages into separate views.

### PR DESCRIPTION
**Pull request by chrisvanrun**
# Closes #1158 
* decoupling the readers progress from the reader-study detail page (for editors)
* split reader list+progress into 
  * reader list (in page)
  * reader progress (separate page)

# Misc.:
* Uses user group management templates
* Readers now have a badge that shows the number of readers

# Performance
The current load time for the editor page for 110 readers is *12.7s*. 
The new load time is *2.6s* for the reader-study page (for editors) and *6.3s* for the reader progress overview page.

The reader progress overview page is not yet as optimized as I'd like but I am calling it "good enough" .

## Current

https://user-images.githubusercontent.com/7871310/106597360-98cb8680-6556-11eb-8a18-e929a777b2c9.mp4

## This PR

https://user-images.githubusercontent.com/7871310/106597374-9ec16780-6556-11eb-828a-b224ced6639a.mp4

### CODE REVIEW

**Comment by jmsmkn** [comment]
Not reviewed the code but this sounds good! A couple of notes about PR managent:

- As we squash the commits and the PR title becomes the commit title would you be able to update it to something imperative?
- Please also use one of the github keywords rather than addresses (https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by chrisvanrun** [comment]
> 
> 
> Not reviewed the code but this sounds good! A couple of notes about PR management:
> 
>     * As we squash the commits and the PR title becomes the commit title would you be able to update it to something imperative?
> 
>     * Please also use one of the github keywords rather than addresses (https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

@jmsmkn, made some changes. Is this okay?

**Comment by jmsmkn** [comment]
Perfect!

**Review by MikeOverkamp-diag — APPROVED** [review]
LGTM!

**Pull request merged**
